baseURL = 'https://pro.cnnept.com/'
languageCode = 'en-us'
title = 'CNNEPT PRO'

# 修正后的输出目录配置，不要加中括号
publishDir = "public"

# 禁用默认主题，使用我们自己写的 layouts
theme = []

[params]
  whatsapp = "8613561675079"