backend:
  name: git-gateway
  # ！！！请把下面的 [你的用户名] 换成你真实的 GitHub 名字 ！！！
  # 比如：repo: Leo/nept-pro-global
  repo: lhx73421530-design/nept-pro-global
  branch: main

# 图片上传存放路径
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Product Management (发布新产品)"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Main Category", name: "main_category", widget: "select", options: ["Cleaning Tools", "Garden Tools", "Power Tools"] }
      - { label: "Sub Category", name: "sub_category", widget: "select", options: ["Ride-on Sweepers", "Floor Scrubbers", "RC Mowers", "Brush Cutters", "Chain Saws", "Lithium-Ion Series"] }
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Price ($)", name: "price", widget: "string" }
      - { label: "Model Number", name: "model", widget: "string" }
      - { label: "Main Image", name: "image", widget: "image" }
      - { label: "Technical Specs", name: "body", widget: "markdown" }