backend:
  name: github
  repo: lhx73421530-design/nept-pro-global  # 比如 Leo/nept-pro-global
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Product List (产品管理)"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Main Image", name: "image", widget: "image" }
      - { label: "Specs", name: "body", widget: "markdown" }