backend:
  name: git-gateway
  # 显式指定 API 路径，不让它在 Vercel 乱撞
  identity_url: "https://magenta-cucurucho-59a5ea.netlify.app/.netlify/identity"
  gateway_url: "https://magenta-cucurucho-59a5ea.netlify.app/.netlify/git"
  repo: lhx73421530-design/nept-pro-global
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "products"
    label: "Product Management"
    folder: "content/products"
    create: true
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Model Number", name: "model", widget: "string" }
      - { label: "Sub Category", name: "sub_category", widget: "select", options: ["Ride-on Sweepers", "Floor Scrubbers", "RC Mowers", "Brush Cutters", "Chain Saws", "Lithium-Ion Series"] }
      - { label: "Main Image", name: "image", widget: "image" }
      - { label: "Body Content", name: "body", widget: "markdown" }